<a href="https://colab.research.google.com/github/TrybinD/educational-projects/blob/main/ML%20projects/House_pricing/version1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"daniiltrubin","key":"a0e37acddb328217e1f38b5525aa2e78"}'}

In [ ]:
!pip install kaggle -q
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle competitions download -c house-prices-advanced-regression-techniques

  0% 0.00/31.2k [00:00<?, ?B/s]
100% 31.2k/31.2k [00:00<00:00, 26.6MB/s]
  0% 0.00/450k [00:00<?, ?B/s]
100% 450k/450k [00:00<00:00, 56.8MB/s]
  0% 0.00/441k [00:00<?, ?B/s]
100% 441k/441k [00:00<00:00, 60.6MB/s]
  0% 0.00/13.1k [00:00<?, ?B/s]
100% 13.1k/13.1k [00:00<00:00, 12.6MB/s]


Начинаем анализ

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data_train = pd.read_csv("train.csv", index_col="Id")
data_test = pd.read_csv("test.csv")

In [ ]:
data_train.head()

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                    ...                                  
1           60       RL         65.0  ...        WD        Normal    208500
2           20       RL         80.0  ...        WD        Normal    181500
3           60       RL         68.0  ...        WD        Normal    223500
4           70       RL         60.0  ...        WD       Abnorml    140000
5           60       RL         84.0  ...        WD        Normal    250000

[5 rows x 80 columns]

In [ ]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   int64  
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          91 non-null     object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [ ]:
analis_cols = ["SalePrice", "LotArea", "YearBuilt", "GarageArea", "GarageCars"]

**Подготовка данных**

In [ ]:
X, y = data_train.drop('SalePrice', axis=1), data_train['SalePrice']

In [ ]:
cat_cols = []
num_cols = []
for i in X:
  if data_train[i].dtype == "object":
    cat_cols.append(i)
  else:
    num_cols.append(i)

In [ ]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder,FunctionTransformer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.impute import SimpleImputer

In [ ]:
def selector(cols):
  return FunctionTransformer(lambda x: x[cols].values) # будет полезно для создания общего пайплайна обработки данных 

In [ ]:
num_pipeline = Pipeline([
                         ("selector", selector(num_cols)), # выбираем только численные значения
                         ("imputer", SimpleImputer(strategy="median")), # у нас в основном не нормальное, а логнормальное - лучше выбрать медиану
                         ("scaler", StandardScaler())])

In [ ]:
cat_pipeline = Pipeline([
                         ("selector", selector(cat_cols)), # выбираем только номинальные значения
                         ("imputer", SimpleImputer(strategy="most_frequent")), # что-то я туплю нужно бы делать как в скобочках но не выходит (у нас порпуски в категориальных значениях обозначают отсутствие чего-либо)
                         ("encoder", OrdinalEncoder()), # OH может столкнуться с проклятьем размерности...
                         ("scaler", StandardScaler()) # Почему бы и нет) 
])

In [ ]:
full_pipeline = FeatureUnion([
                             ("cat", cat_pipeline),
                             ("num", num_pipeline)
]) # теперь нам не надо прыгать с бубном обрабатывая тестовую выборку 

In [ ]:
X_prepeared = full_pipeline.fit_transform(X)

In [ ]:
X_prepeared.shape

(1460, 79)

Попробуем альтернативы

In [ ]:
cat_pipeline2 = Pipeline([
                         ("selector", selector(cat_cols)), # выбираем только номинальные значения
                         ("imputer", SimpleImputer(strategy="most_frequent")), # что-то я туплю нужно бы делать как в скобочках но не выходит (у нас порпуски в категориальных значениях обозначают отсутствие чего-либо)
                         ("encoder", OneHotEncoder(sparse=False)), # ээээксперементы
                         ("scaler", StandardScaler()) # Почему бы и нет) 
])

In [ ]:
full_pipeline2 = FeatureUnion([
                             ("cat", cat_pipeline2),
                             ("num", num_pipeline)
]) # теперь нам не надо прыгать с бубном обрабатывая тестовую выборку 

In [ ]:
X_prepeared = full_pipeline2.fit_transform(X)

In [ ]:
X_prepeared.shape

(1460, 288)

**Первая базовая модель**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [ ]:
rf_reg = RandomForestRegressor()

In [ ]:
cross_val_score(rf_reg, X_prepeared, y, cv=5, scoring="neg_mean_squared_log_error")

array([-0.01898747, -0.02341357, -0.02014594, -0.01859329, -0.0237999 ])

In [ ]:
rf_reg.fit(X_prepeared, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

Предсказание базоваой моделью и отправка

In [ ]:
X_test = data_test.drop(["Id"],axis=1)
X_test

MSSubClass MSZoning  LotFrontage  ...  YrSold SaleType SaleCondition
0             20       RH         80.0  ...    2010       WD        Normal
1             20       RL         81.0  ...    2010       WD        Normal
2             60       RL         74.0  ...    2010       WD        Normal
3             60       RL         78.0  ...    2010       WD        Normal
4            120       RL         43.0  ...    2010       WD        Normal
...          ...      ...          ...  ...     ...      ...           ...
1454         160       RM         21.0  ...    2006       WD        Normal
1455         160       RM         21.0  ...    2006       WD       Abnorml
1456          20       RL        160.0  ...    2006       WD       Abnorml
1457          85       RL         62.0  ...    2006       WD        Normal
1458          60       RL         74.0  ...    2006       WD        Normal

[1459 rows x 79 columns]

In [ ]:
X_test_prep = full_pipeline.transform(X_test)

In [ ]:
X_test_prep.shape

(1459, 79)

In [ ]:
y_pred = rf_reg.predict(X_test_prep) 

In [ ]:
y_pred

array([127231.5 , 154115.9 , 180720.24, ..., 152129.51, 119373.83,
       227730.26])

In [ ]:
ans = pd.DataFrame({"Id": data_test.Id,"SalePrice": y_pred})

In [ ]:
ans.to_csv("submission2.csv", index=False)

In [ ]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f submission2.csv -m "Message"

100% 20.9k/20.9k [00:00<00:00, 81.0kB/s]
Successfully submitted to House Prices - Advanced Regression Techniques

Эксперементы с моделями и поиск по сетке

In [ ]:
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostRegressor, BaggingRegressor, GradientBoostingRegressor

In [ ]:
svm_reg = SVR()
ada_reg = AdaBoostRegressor()
bag_reg = BaggingRegressor()
gb_reg = GradientBoostingRegressor()

In [ ]:
estims = [rf_reg, gb_reg, ada_reg, bag_reg]

In [ ]:
for estim in estims:
  print(cross_val_score(estim, X_prepeared, y, scoring="neg_mean_squared_log_error", cv=5))

[-0.01875325 -0.02323763 -0.02053194 -0.01938186 -0.0242315 ]
[-0.01348869 -0.02139104 -0.01879308 -0.01543384 -0.01734532]
[-0.03266295 -0.04736249 -0.03639981 -0.04219618 -0.03958879]
[-0.02095311 -0.02740978 -0.02351032 -0.02085338 -0.02643849]


In [ ]:
y_pred_matrix = []
for estim in estims:
  estim.fit(X_prepeared, y)
  y_pred_matrix.append(estim.predict(X_test_prep))

np.corrcoef(y_pred_matrix)

array([[1.        , 0.9890173 , 0.96653096, 0.99062895],
       [0.9890173 , 1.        , 0.96551561, 0.98316864],
       [0.96653096, 0.96551561, 1.        , 0.95897393],
       [0.99062895, 0.98316864, 0.95897393, 1.        ]])

In [ ]:
from sklearn.ensemble import VotingRegressor

In [ ]:
vot_reg = VotingRegressor([
                           ("rf", rf_reg),
                           ("ada", ada_reg),
                           ("bag", bag_reg),
                           ("gb", gb_reg)
])

In [ ]:
cross_val_score(vot_reg, X_prepeared, y, scoring="neg_mean_squared_log_error", cv=5)

array([-0.01751173, -0.02599803, -0.02117094, -0.02098813, -0.02347144])

In [ ]:
vot_reg.fit(X_prepeared, y)

VotingRegressor(estimators=[('rf',
                             RandomForestRegressor(bootstrap=True,
                                                   ccp_alpha=0.0,
                                                   criterion='mse',
                                                   max_depth=None,
                                                   max_features='auto',
                                                   max_leaf_nodes=None,
                                                   max_samples=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   n_estimators=100,
                                     

In [ ]:
y_pred = vot_reg.predict(X_test_prep) 
ans = pd.DataFrame({"Id": data_test.Id,"SalePrice": y_pred})
ans.to_csv("submission4.csv", index=False)

In [ ]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f submission4.csv -m "Message"

100% 33.7k/33.7k [00:00<00:00, 160kB/s]
Successfully submitted to House Prices - Advanced Regression Techniques

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
rf_params = {
    "n_estimators": [40, 50, 70, 100],
    "max_depth": [500, 700, 1000]
}

grid_rf = GridSearchCV(rf_reg, rf_params, scoring="neg_mean_squared_log_error", cv=5)
grid_rf.fit(X_prepeared, y)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='deprecated', n_jo

In [ ]:
grid_rf.best_score_, grid_rf.best_estimator_

(-0.021221360921114492,
 RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                       max_depth=500, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False))

In [ ]:
y_pred = grid_rf.best_estimator_.predict(X_test_prep) 
ans = pd.DataFrame({"Id": data_test.Id,"SalePrice": y_pred})
ans.to_csv("submission5.csv", index=False)

In [ ]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f submission5.csv -m "Message"

100% 20.9k/20.9k [00:00<00:00, 99.6kB/s]
Successfully submitted to House Prices - Advanced Regression Techniques

Попробуем немножечко читов

In [ ]:
X_big = X.append(X_test)

In [ ]:
X_big

MSSubClass MSZoning  LotFrontage  ...  YrSold SaleType SaleCondition
1             60       RL         65.0  ...    2008       WD        Normal
2             20       RL         80.0  ...    2007       WD        Normal
3             60       RL         68.0  ...    2008       WD        Normal
4             70       RL         60.0  ...    2006       WD       Abnorml
5             60       RL         84.0  ...    2008       WD        Normal
...          ...      ...          ...  ...     ...      ...           ...
1454         160       RM         21.0  ...    2006       WD        Normal
1455         160       RM         21.0  ...    2006       WD       Abnorml
1456          20       RL        160.0  ...    2006       WD       Abnorml
1457          85       RL         62.0  ...    2006       WD        Normal
1458          60       RL         74.0  ...    2006       WD        Normal

[2919 rows x 79 columns]

In [ ]:
full_pipeline.fit(X_big)

FeatureUnion(n_jobs=None,
             transformer_list=[('cat',
                                Pipeline(memory=None,
                                         steps=[('selector',
                                                 FunctionTransformer(accept_sparse=False,
                                                                     check_inverse=True,
                                                                     func=<function selector.<locals>.<lambda> at 0x7fb5939f3cb0>,
                                                                     inv_kw_args=None,
                                                                     inverse_func=None,
                                                                     kw_args=None,
                                                                     validate=False)),
                                                ('imputer',
                                                 SimpleImputer(add_indicator=False,
                     

In [ ]:
X_prepeared = full_pipeline.transform(X)
X_test_prep = full_pipeline.transform(X_test)

In [ ]:
best_rf_reg = grid_rf.best_estimator_

In [ ]:
best_rf_reg.fit(X_prepeared, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=500, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
y_pred = best_rf_reg.predict(X_test_prep) 
ans = pd.DataFrame({"Id": data_test.Id,"SalePrice": y_pred})
ans.to_csv("submission6.csv", index=False)

In [ ]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f submission6.csv -m "Message"